### ISSUE TITLE
Monsters can move the fixed blocks and bananas together

### ISSUE THREAD

**Issue by klsdfr** [BenjaminRi/Banania#2] opened 2022-09-13 08:03 UTC
When trying to reproduce the error concerning #1 I experienced this error, I had a few times in the higher levels.
![image](https://user-images.githubusercontent.com/1910772/189845196-6aa58d73-85da-44ec-9c64-0f8e2325565d.png)

The monsters sometimes have the ability to move the fixed blocks and bananas (nevermind my changed banana graphic to a bitcoin 😅). It also seems like the problem only happens if 2 monsters are on the same spot. 🤔

**Comment by BenjaminRi** [comment] 2022-09-18 13:45
The issue is fixed with commit a89488d602511ff8a775e6058b78102f3f6d3045 (currently HEAD of master)

There was an issue with the logic that decided where entities (in particular, monsters) can move. However, the walkability check code could use a larger rework (well, the entire code could use a rework), I believe there might still be some subtle issues with pushing blocks simultaneously from multiple directions.

Please let me know if it works for you now. I'm always happy to hear from people who play or modify the game.

**Closed as completed by BenjaminRi** 2022-09-18 13:45 UTC
